# Generated by Django 5.2 on 2025-04-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_creat5ed',
            new_name='is_created',
        ),
    ]
